config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments
    

end
resources :books
resources :welcome

end

app/models/article.rb
#class GoodnessValidator<ActiveModel::Validator
	#def validate(record)
		#if record.title = "Mukesh"
			#record.errors[:base]<<"This is not mukesh"
	#end
#end
#end


class Article < ActiveRecord::Base
	has_many :comments
	validates :title ,presence: {strict: true},length: {minimum: 5} ,confirmation: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }, allow_blank: true, if: "title.nil?"
	validates :check, acceptance: true
	validates_associated :comments

	 validates :title_confirmation ,presence: true 
	  #validates_with GoodnessValidator
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :body , presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "customlayout"
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
    @articles = Article.all

  end
 
  def show
    @article = Article.find(params[:id])
    @comment = @article.comments.build 
  end
 
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
 def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path

  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text, :check,:title_confirmation)
    end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books=Book.all
		#render inline: "<h1>Hello</h1>"
		#render plain: "OK"

		
		#render html: "<b>Helloo....Neno</b>".html_safe
		#render json: @books
		#render xml: @books
		##render js: "alert('Hello....rails');"

		#render body: "raw"

		
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
 
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	#render 'articles/new' 

  	#render '/nensi/App1/app/views/greeting/Hello'

  	#render 'articles/new', content_type: "text/css"

  	#render layout: "customlayout"
  	#render layout: false

  	#render status: 500
#render status: :forbidden
#render location: '/blog/app/assets/images/neno.jpg'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<table>
  
 
  
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%=link_to 'Edit',edit_article_path(article) %><td>
        <td><%=link_to 'Delete',article_path(article),method: :delete ,data: {confirm: 'Are you sure?'}%></td>
    </tr>
  
</table>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
     <%= f.text_field :title_confirmation %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 <p>

  <%=f.check_box  :check %>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 <table>
<tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 </table>
<%= render partial: "article", collection: @articles , locals: {article: @article}%>

app/views/articles/new.html.erb
<h1> New article</h1>
 
<%= render 'form' %>
	<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/books/index.html.erb
<h1>Listing Book</h1>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/index.html.erb
<h1>Index</h1	>

app/views/comments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Add a comment:</h2>
<%= form_for([@article, @comment]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/customlayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h1>Hiiiiiiiiiiiii..........Neno</h1>
</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h1>Special</h1>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello......</h1>